Add files via upload
Sorry, cannot upload shape_predictor_68_face_landmarks.dat because it's too large. Please add it if you need to run the code, thank you!
Error: Yowza, that’s a big file. Try again with a file smaller than 25MB.